export enum City {
  NEW_YORK = 'new_york',
  LOS_ANGELES = 'los_angeles',
  CHICAGO = 'chicago',
  HOUSTON = 'houston',
  PHOENIX = 'phoenix',
  PHILADELPHIA = 'philadelphia',
  SAN_ANTONIO = 'san_antonio',
  SAN_DIEGO = 'san_diego',
  DALLAS = 'dallas',
  SAN_JOSE = 'san_jose',
  AUSTIN = 'austin',
  JACKSONVILLE = 'jacksonville',
  SAN_FRANCISCO = 'san_francisco',
  COLUMBUS = 'columbus',
  FORT_WORTH = 'fort_worth',
}

export const CityDisplayLabels: Record<City, string> = {
  [City.NEW_YORK]: 'New York',
  [City.LOS_ANGELES]: 'Los Angeles',
  [City.CHICAGO]: 'Chicago',
  [City.HOUSTON]: 'Houston',
  [City.PHOENIX]: 'Phoenix',
  [City.PHILADELPHIA]: 'Philadelphia',
  [City.SAN_ANTONIO]: 'San Antonio',
  [City.SAN_DIEGO]: 'San Diego',
  [City.DALLAS]: 'Dallas',
  [City.SAN_JOSE]: 'San Jose',
  [City.AUSTIN]: 'Austin',
  [City.JACKSONVILLE]: 'Jacksonville',
  [City.SAN_FRANCISCO]: 'San Francisco',
  [City.COLUMBUS]: 'Columbus',
  [City.FORT_WORTH]: 'Fort Worth',
};
