export enum Specialty {
  BIPOLAR = 'bipolar',
  LGBTQ = 'lgbtq',
  MEDICATION_PRESCRIBING = 'medication_prescribing',
  SUICIDE_HISTORY = 'suicide_history',
  GENERAL_MENTAL_HEALTH = 'general_mental_health',
  MENS_ISSUES = 'mens_issues',
  RELATIONSHIP_ISSUES = 'relationship_issues',
  TRAUMA_AND_PTSD = 'trauma_and_ptsd',
  PERSONALITY_DISORDERS = 'personality_disorders',
  PERSONAL_GROWTH = 'personal_growth',
  SUBSTANCE_USE = 'substance_use',
  PEDIATRICS = 'pediatrics',
  WOMENS_ISSUES = 'womens_issues',
  CHRONIC_PAIN = 'chronic_pain',
  WEIGHT_LOSS_NUTRITION = 'weight_loss_nutrition',
  EATING_DISORDERS = 'eating_disorders',
  DIABETIC_DIET_NUTRITION = 'diabetic_diet_nutrition',
  COACHING = 'coaching',
  LIFE_COACHING = 'life_coaching',
  OBSESSIVE_COMPULSIVE_DISORDERS = 'obsessive_compulsive_disorders',
  NEUROPSYCHOLOGICAL_TESTING = 'neuropsychological_testing',
  ADHD = 'adhd',
  SLEEP_ISSUES = 'sleep_issues',
  SCHIZOPHRENIA_PSYCHOTIC_DISORDERS = 'schizophrenia_psychotic_disorders',
  LEARNING_DISORDERS = 'learning_disorders',
  DOMESTIC_ABUSE = 'domestic_abuse',
}

export const SpecialtyDisplayLabels: Record<Specialty, string> = {
  [Specialty.BIPOLAR]: 'Bipolar',
  [Specialty.LGBTQ]: 'LGBTQ',
  [Specialty.MEDICATION_PRESCRIBING]: 'Medication/Prescribing',
  [Specialty.SUICIDE_HISTORY]: 'Suicide History/Attempts',
  [Specialty.GENERAL_MENTAL_HEALTH]:
    'General Mental Health (anxiety, depression, stress, grief, life transitions)',
  [Specialty.MENS_ISSUES]: "Men's issues",
  [Specialty.RELATIONSHIP_ISSUES]:
    'Relationship Issues (family, friends, couple, etc)',
  [Specialty.TRAUMA_AND_PTSD]: 'Trauma & PTSD',
  [Specialty.PERSONALITY_DISORDERS]: 'Personality disorders',
  [Specialty.PERSONAL_GROWTH]: 'Personal growth',
  [Specialty.SUBSTANCE_USE]: 'Substance use/abuse',
  [Specialty.PEDIATRICS]: 'Pediatrics',
  [Specialty.WOMENS_ISSUES]:
    "Women's issues (post-partum, infertility, family planning)",
  [Specialty.CHRONIC_PAIN]: 'Chronic pain',
  [Specialty.WEIGHT_LOSS_NUTRITION]: 'Weight loss & nutrition',
  [Specialty.EATING_DISORDERS]: 'Eating disorders',
  [Specialty.DIABETIC_DIET_NUTRITION]: 'Diabetic Diet and nutrition',
  [Specialty.COACHING]: 'Coaching (leadership, career, academic and wellness)',
  [Specialty.LIFE_COACHING]: 'Life coaching',
  [Specialty.OBSESSIVE_COMPULSIVE_DISORDERS]: 'Obsessive-compulsive disorders',
  [Specialty.NEUROPSYCHOLOGICAL_TESTING]:
    'Neuropsychological evaluations & testing (ADHD testing)',
  [Specialty.ADHD]: 'Attention and Hyperactivity (ADHD)',
  [Specialty.SLEEP_ISSUES]: 'Sleep issues',
  [Specialty.SCHIZOPHRENIA_PSYCHOTIC_DISORDERS]:
    'Schizophrenia and psychotic disorders',
  [Specialty.LEARNING_DISORDERS]: 'Learning disorders',
  [Specialty.DOMESTIC_ABUSE]: 'Domestic abuse',
};
